version: "3.8"
services:
  backend:
    container_name: mancala-backend
    build: ./
    image: bolcom/mancala-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
  frontend:
    container_name: mancala-frontend
    build: ./src/main/frontend
    image: bolcom/mancala-frontend
    ports:
      - "3000:3000"